import { jsPDF } from 'jspdf';
import { Chronometer } from '../types';
import { formatTime, formatDelta } from './time';

function getFastestSlowest(laps: Chronometer['laps']) {
  if (laps.length < 2) {
    return { fastest: -1, slowest: -1 };
  }

  const fastest = laps.reduce(
    (min, lap, i) => (lap.lapTime < laps[min].lapTime ? i : min),
    0,
  );

  const slowest = laps.reduce(
    (max, lap, i) => (lap.lapTime > laps[max].lapTime ? i : max),
    0,
  );

  return { fastest, slowest };
}

export async function exportAndShare(
  chronos: Chronometer[],
  getDisplayElapsed: (c: Chronometer) => number,
): Promise<void> {
  if (chronos.length === 0) {
    return;
  }

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const drawBackground = () => {
    doc.setFillColor(242, 242, 247);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
  };

  drawBackground();

  let y = 20;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(26);
  doc.setTextColor(0, 122, 255);
  doc.text('MultiChrono', 20, y);

  y += 8;

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(142, 142, 147);
  doc.text(
    `Exported on ${new Date().toLocaleString()}`,
    20,
    y,
  );

  y += 12;

  for (const chrono of chronos) {
    const elapsed = getDisplayElapsed(chrono);

    const cardHeight =
      chrono.laps.length > 0
        ? 28 + chrono.laps.length * 8
        : 32;

    if (y + cardHeight > pageHeight - 20) {
      doc.addPage();
      drawBackground();
      y = 20;
    }

    // Card
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(
      15,
      y,
      180,
      cardHeight,
      4,
      4,
      'F',
    );

    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(28, 28, 30);

    doc.text(chrono.name, 22, y + 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(18);

    doc.text(
      formatTime(elapsed),
      188,
      y + 10,
      { align: 'right' },
    );

    y += 18;

    if (chrono.laps.length > 0) {
      // Table header
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(142, 142, 147);

      doc.text('LAP', 22, y);
      doc.text('TIME', 50, y);
      doc.text('Δ DELTA', 95, y);
      doc.text('TOTAL', 145, y);

      y += 6;

      const { fastest, slowest } =
        getFastestSlowest(chrono.laps);

      chrono.laps.forEach((lap, idx) => {
        if (idx === fastest) {
          doc.setFillColor(200, 245, 213);
          doc.rect(18, y - 4.5, 170, 7, 'F');
        } else if (idx === slowest) {
          doc.setFillColor(255, 208, 206);
          doc.rect(18, y - 4.5, 170, 7, 'F');
        }

        doc.setFont('courier', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(28, 28, 30);

        doc.text(`#${lap.number}`, 22, y);

        doc.text(
          formatTime(lap.lapTime),
          50,
          y,
        );

        doc.text(
          lap.number === 1
            ? '—'
            : formatDelta(lap.delta),
          95,
          y,
        );

        doc.text(
          formatTime(lap.accumulated),
          145,
          y,
        );

        y += 8;
      });
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(142, 142, 147);

      doc.text(
        'No laps recorded',
        22,
        y,
      );

      y += 10;
    }

    y += 10;
  }

  // Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(198, 198, 200);

  doc.text(
    'Generated by MultiChrono',
    pageWidth / 2,
    pageHeight - 10,
    {
      align: 'center',
    },
  );

  const pdfBlob = doc.output('blob');

  const pdfFile = new File(
    [pdfBlob],
    'multichrono-report.pdf',
    {
      type: 'application/pdf',
    },
  );

  if (
    navigator.canShare &&
    navigator.canShare({ files: [pdfFile] })
  ) {
    try {
      await navigator.share({
        files: [pdfFile],
        title: 'MultiChrono Results',
        text: 'MultiChrono results',
      });
      return;
    } catch (err) {
      console.log('Share cancelled:', err);
    }
  }

  doc.save('multichrono-report.pdf');
}